### ISSUE TITLE
Andriod download directory

### ISSUE THREAD

**Issue by TuxPaper** [BiglySoftware/BiglyBT-Android#105]
_From @luckiestone on April 8, 2018 9:58_

Hi,
I'm using BiglyBT with my android TV box Zidoo X10, which works perfect unless I can't choose an arbitrary directory to download my movies to. It's only possible to choose one of the provided ones.
Is it possible to add an option that we can choose any fold as a download directory? Or is this just an Android development restriction?

_Copied from original issue: BiglySoftware/BiglyBT#434_

**Comment by erichlotto** [comment]
This is the only feature I'm currently missing. I need to point each of my rss to a different download location...

**Comment by br1panic** [comment]
Could I ask you if you planned to add this feature? And if yes, when do you think it will be available? I have an external storage and I can't save locally because there is no space.
The app is fantastic!! 
Thank you so much
Bruno

**Comment by TuxPaper** [comment]
Something will be in the next release.  There's a few other bugs/issues about the directory selection that needs fixing too.  We just finished our desktop client release, so I can now start focusing on this.  Hopefully that means a release in a week or two, depending on how many times I have to swear at Android's filesystem handling ;)

**Comment by TuxPaper** [comment]
Latest version (1.2.4) should fix this, plus allow you to select any writable path

**Comment by br1panic** [comment]
Dears,
 I just installed the last version 1.2.4 but I can't find the option to change the download directory. I'm really sorry if I didn't find it. Could you help me?

**Comment by TuxPaper** [comment]
On the Open Torrent window, there's a folder icon next to "Save Location" text.

For existing torrents, you can either long tap a torrent and choose "Change Save Folder" from the action (bar) menu. Or you can tap on the torrent to get to the torrent screen, and the "Change Save Folder" will be in the drawer under "Actions"

**Comment by br1panic** [comment]
Nice! I found the option. Thank you so much for your help.

Kim regards

**Comment by TuxPaper** [comment]
Note on existing large torrents it may take a while to move and there's no progress indicator (yet!  It's scandalous!), so the location field may not immediately update.

**Comment by br1panic** [comment]
Sorry if I'm writing you again. Just a doubt, I use BiglyBT installed on my TV box, and I search torrents from my mobile, and I start the download of the torrents remotely from my mobile. I have a USB hard disk plugged to the TV box because it doesn't have much disk space. Anyway if I start the download from my mobile remotely, I suppose there is no way to change the destination folder where the torrents will be downloaded. Is it correct? Because I supposed it was possible to set the download folder from the main menu setting of BiglyBT for all the downloaded files, not setting the download for each torrent every time you download a new file. Sorry if it's a stupid question, but I know that BiglyBT is one of the best server for downloading torrent remotely.

Thank you for your patience
