### ISSUE TITLE
BiglyBT-core.jar

### ISSUE THREAD

**Issue by Shusshu** [BiglySoftware/BiglyBT-Android#17]
Instead of a jar lib in git would it be better to have an external dependency ?

With this PR https://github.com/BiglySoftware/BiglyBT/pull/101 it is very easy to achieve using jitpack.io

**Comment by TuxPaper** [comment]
An external dependency would be best, but right now, BiglyBT-core.jar is actually a subset of the core (I guess I should have called it BiglyBT-android-core.jar), with most (but not all! :disappointed: ) of the `uis` module excluded, and some android specific patches I have yet to commit into the main repo (they are simple changes such as using reflection to call J8 classes that Android doesn't have)

Sometime in the future, I'll document what is included and removed (fwiw, the v1.1.0 tag has the stripped core source, because it was needed for f-droid acceptance)

**Comment by TuxPaper** [comment]
Once I have the Android specific code committed to the main BiglyBT repo, the following includes/excludes should build a proper BiglyBT-android-core.jar

From my `BiglyBT.iml`
```
      <sourceFolder url="file://$MODULE_DIR$/core/src" isTestSource="false" />
      <sourceFolder url="file://$MODULE_DIR$/uis/src" isTestSource="false" />
      <excludeFolder url="file://$MODULE_DIR$/core/src/com/biglybt/core/util/dns" />
      <excludeFolder url="file://$MODULE_DIR$/core/src/com/biglybt/core/util/jman" />
      <excludeFolder url="file://$MODULE_DIR$/core/src/com/biglybt/internat" />
      <excludeFolder url="file://$MODULE_DIR$/core/src/com/biglybt/pifimpl/remote" />
      <excludeFolder url="file://$MODULE_DIR$/core/src/com/biglybt/platform/macosx" />
      <excludeFolder url="file://$MODULE_DIR$/core/src/com/biglybt/platform/unix" />
      <excludeFolder url="file://$MODULE_DIR$/core/src/com/biglybt/platform/win32" />
      <excludeFolder url="file://$MODULE_DIR$/uis/lib" />
      <excludeFolder url="file://$MODULE_DIR$/uis/src/com/biglybt/core" />
      <excludeFolder url="file://$MODULE_DIR$/uis/src/com/biglybt/plugin" />
      <excludeFolder url="file://$MODULE_DIR$/uis/src/com/biglybt/ui/common" />
      <excludeFolder url="file://$MODULE_DIR$/uis/src/com/biglybt/ui/console" />
      <excludeFolder url="file://$MODULE_DIR$/uis/src/com/biglybt/ui/icons" />
      <excludeFolder url="file://$MODULE_DIR$/uis/src/com/biglybt/ui/images" />
      <excludeFolder url="file://$MODULE_DIR$/uis/src/com/biglybt/ui/skin" />
      <excludeFolder url="file://$MODULE_DIR$/uis/src/com/biglybt/ui/swing" />
      <excludeFolder url="file://$MODULE_DIR$/uis/src/com/biglybt/ui/swt" />
      <excludeFolder url="file://$MODULE_DIR$/uis/src/com/biglybt/ui/telnet" />
      <excludeFolder url="file://$MODULE_DIR$/uis/src/org" />
```

From my `compiler.xml`
```
    <excludeFromCompile>
      <file url="file://$PROJECT_DIR$/core/src/com/biglybt/platform/unix/ScriptBeforeStartup.java" />
      <file url="file://$PROJECT_DIR$/uis/src/com/biglybt/ui/Main.java" />
      <file url="file://$PROJECT_DIR$/core/src/com/biglybt/ui/webplugin/WebPluginAccessController.java" />
    </excludeFromCompile>
```

**Comment by Shusshu** [comment]
I think we can do a temp maven profile to generate this biglybt-android following these excludes but it's not a very good solution....

What we can do instead is reorganise biglybt in 4 modules instead of 2

- core
- core-pif
- ui-common
- ui-swt (current uis with a bit less stuff )

**Comment by TuxPaper** [comment]
I wonder about an alternative approach, but I'm not sure if it's possible or a good idea.  Have a BiglyBT-Android-Core branch with those files excluded, and have the branch auto-merge from trunk.

**Comment by Shusshu** [comment]
Why not... I don't know how to setup a repo with auto-merge + exclude but it would certainly be interesting to see that in action :)

**Comment by Shusshu** [comment]
Have you had the chance to commit the android specific patches on biglybt core?

**Comment by davisjackie321** [comment]
Ye

**Comment by Shusshu** [comment]
Any news on this one?

**Comment by TuxPaper** [comment]
I don't have any automatic merging setup between the android branch and master.  For now, I'll do it manually whenever I update the BiglyBT-core.jar at https://github.com/BiglySoftware/BiglyBT-Android/tree/master/BiglyBT/libs

I'm sure there's some way to make the maven build go to some gradle repo, so that the Android projects build.gradle could just add the dependency, but I haven't looked into it.

**Comment by Shusshu** [comment]
You can setup another github repo as a maven repository

**Comment by TuxPaper** [comment]
core is now a submodule, as well as all the plugins
