### ISSUE TITLE
Connection is "stopped" after a while

### ISSUE THREAD

**Issue by misibacsi** [BiglySoftware/BiglyBT-Android#212]
Hello

I have the a problem, that the server says "stopped".
D/L goes without problems.

When the BiglyBT starts to seed a torrent, it is OK for a while, but the server - with which BiglyBT connects - says: "stopped".
Then I have to do by hand a Stop / Start on the torrent, and the server is happy again, says "seed".

In BiglyBT I always see that the connection is OK, it says "seeding".
But at the same time the server says "stopped". 
Once I even could see some active peers connecting to me.

Questions:
1. What may cause this? 
2. Would it be possible to implement a diagnostic function to see what happens? For example to see a log of the communication.
3. It would be an easy workaround, if BiglyBT would do an  automatic  Stop / Start periodically (every 5, 10, 15, 30 minutes).

I  recommend tha last method, it is easy and always works.

Regards

**Comment by JoshuaGloriod** [comment]
Is the server BiglyBT as well? It's got a pretty much permanent notification saying something like "sleeping because device is not plugged in".

You can fix that behavior in settings, but to notification won't go away. This is probably a workaround for the evil battery savers that manufacturers implement. But you can always sooze the notification if it annoys you.

**Comment by TuxPaper** [comment]
v1.3.3 has been released with the latest core version (3.4).  Please try with the latest version, and if you are still having issues, feel free to open a new ticket
