### ISSUE TITLE
Remote access when bind to VPN interface and vpn is UP [Android TV] [1.3.0.8]

### ISSUE THREAD

**Issue by kyxap** [BiglySoftware/BiglyBT-Android#223]
Hi there,

New BiglyBT user!

I've configured BiglyBT to bind to VPN interface on my android device and all works ok except the remote access.

When I'm trying to enable remote access I see that it enables on the VPN ip/interface (which is not my local) and there no access to BiglyBT service via local ip.

If I disable VPN interface binding the UI remote access works with no issue.

Do I need to add extra bindings to local network if so what is requred? I tried couple things but nothing helped.

Thank you in advance.

**Comment by TuxPaper** [comment]
This was partially fixed in 1.3.2.
If you installed BiglyBT from F-Droid, unfortunately it did not get this release.

If you installed from Google Play, you should be able to get 1.3.2. When you initially change "Allow Remote Control on LAN" on, it will not properly apply when on VPN until you Restart the Torrenting Service (In your notification bar, pull down the BigyBT notification and click the "Restart" button).  I'll fix that quirk in the next release, which should be out this month (as well as a F-Droid release if I can remember how)
