### ISSUE TITLE
Use different peer id than desktop version of BiglyBT

### ISSUE THREAD

**Issue by proton-ab** [BiglySoftware/BiglyBT-Android#74]
Please use different peer id to differentiate between mobile and desktop clients. If this issue is not satisfied, we can not continue whitelisting this client. Additional points (both related and unrelated) quoted from my posts on AnimeBytes

> Additionally the core library used by Android application is provided in form of compiled Java classes - https://github.com/BiglySoftware/BiglyBT-Android/tree/master/BiglyBT/libs. While commit implies it comes from https://github.com/BiglySoftware/BiglyBT/tree/android there is really no way to verify it. It also seems that Android application announces itself as BiglyBT 1.5 (https://github.com/BiglySoftware/BiglyBT/blob/android/core/src/com/biglybt/core/util/Constants.java#L159) which is strictly incorrect as you can see that 'android' branch has diverged from 'master' branch (This branch is 15 commits ahead, 16 commits behind master.). We are now in situation where two different clients announce as one and we're considering this to be spoofing on part of BiglyBT Android application to imitate desktop client.

Irrelevant of our no mobile client policy which is a part of why BiglyBT is now blacklisted, there is an issue of two clients that are going to potentially diverge further away in terms of functions are announcing as same client.

**Comment by TuxPaper** [comment]
We'll do something about the peer id in the next android release.   Although, changing the peer id for Android only will make the code diverge even more.  Is peerid the only way to black/whitelist a client, or are there other fields we could use?  Even an extra parameter send to the tracker might be more optimal.  ie. a client-type url parameter, something like `ct=android` and `ct=desktop`

To address what you quoted (and thanks for quoting it), if you or the admins look at the core android branch's commit's https://github.com/BiglySoftware/BiglyBT/compare/master...android you will see it consists of two types changes:
* Gradle script changes to exclude the UI
* Android doesn't have some Java features (try-with-resource, FileTime, Long.compare, etc) so these are converted into something android can handle.

Building from the Gradle file will produce the exact .jar that's committed in the "libs" directory of BiglyBT-Android. The only reason we have a BiglyBT.jar committed now is so that we don't have the bloat of all those unneeded java files while developing in Android Studio. 

It should also be of note that the release on F-Droid is built by the F-Droid team, and it build purely from source (no JAR files). https://f-droid.org/en/packages/com.biglybt.android.client/  To prove that we aren't injecting secret source code in the apk, I'm not sure how much more "verify-ie" we can be.

In a perfect world, we wouldn't have the android branch of the core, but there's not much we can do about Android not having Long.compare.  As time goes on, and android starts supporting java features/APIs we use, the branch will look more and more like trunk.  Just recently Android added support for default interface methods, which reduced the amount of changes we had quite a bit.

Out of curiosity, do you know the reasoning for banning mobile torrent apps?  Other than it's stupid to have a torrent client running on your phone? ;)  For things like Android TV and Android TV Boxes, that are on 24/7 with ethernet, there's really no difference between them and a desktop client.  I'd almost guess that Android TV apps are sharing more, because people forget that they are always on.

**Comment by proton-ab** [comment]
About additional field, we will accept only such solution if it goes via proper BitTorrent Proposal procedure and gets widely accepted. Until then we will use peer id to distinguish clients as everyone else does and it should be your responsibility to follow others if you also want to get widely accepted in community. That being said I can see your proposal gaining some traction as mobile clients (be it Android TV boxes or Chromebooks) gets more popular so don't be afraid to make a formal BIP out of it.

Addressing divergence issue - I'm sure that it will diverge further in future either way, due to various reasons and platform differences that are also reason for us banning mobile clients (see below). 

As for validating source code, it would be best if instead it was git module dependency to android branch on BiglyBT repo - that way everyone will be happy and we avoid unnecessary issues.

There are various reasons why we don't allow mobile clients. I won't be getting deep into a lot of them because that's not the point of this issue, however the few main issues are battery life, issues with seeding via mobile network, swarm health (constant disconnections), space on device and most importantly, memory/background-app manager on mobile devices that not only increases all of the above issues (especially issues with seeding, swarm health and constant disconnections) but also may (and often does) cause faulty reports to tracker. While these issues are moot point for public trackers, they are essential for maintaining healthy swarm and economy on private trackers. All of these issues, except for last one, are caused by seeding from mobile devices and are not present when seeding from example Android TV box - however another issue arises that is - how to distinguish between them and how to whitelist one while not allowing another? As you can see this is indeed a bigger and more complex problem that takes on issues that would require going to drawing board and changing how Android (for example) manages background activity and saves battery life, which is going to become even more of an issue with Android P on the horizon.

**Comment by BiglyBT** [comment]
Latest android version (1.1.9) now has an 'A' in the 9th position (array position 8)
For example, -BI5701-A...........
